/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        'light-action': "#8990d9",
        'light-action-hover': "#808cc5",
        'light-action-active': "#6074af",
        'light-menu': "#dcdaf3",
        'light-menu-hover': "#dcdaf3",
        'light-accent': "#FCBB6D",
        'light-accent-red': "#d62828",
        'light-accent-orange': "#f77f00",
        'light-accent-yellow': "#fcbf49",
        'light-accent-wheat': "#eae2b7",
        'light-bg': "#dcdaf3",
        'light-bg-alt': "#fffffd",
        "light-input-bg": "#d0d5ea",
        "light-input-bg-edit": "#c5d0e6",
        'light-zebra-odd': "#dFe9f7",
        'light-zebra-even': "#fdf4ff",
        'light-bg-selected': "#70788e",
        'light-health-up-bg': "#55a320",
        'light-health-down-bg': "#c42f4e",
        'dark-action': "#685D79",
        'dark-action-hover': "#AB6C82",
        'dark-action-active': "#6A607C",
        'dark-action-light': "#707182",
        'dark-menu': "#3C516E",
        'dark-menu-hover': "#475C7A",
        'dark-accent': "#FCBB6D",
        'dark-accent-red': "#D8737F",
        'dark-accent-orange': "#FCB86A",
        'dark-accent-yellow': "#FCBB6D",
        'dark-accent-wheat': "#eae2b7",
        'dark-bg': "#475C7A",
        'dark-bg-alt': "#425978",
        'dark-bg-selected': "#202736",
        'dark-content-bg': "#111827",
        'dark-input-bg': "#40455a",
        'dark-input-bg-edit': "#3a4056",
        'dark-input-bg-selected': "#70788e",
        'dark-zebra-odd': "#1F2937",
        'dark-zebra-even': "#3d445f",
        'dark-health-up-bg': "#358300",
        'dark-health-down-bg': "#a40f2e"
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography')
  ],
}
