name: Campaigner App Tester
run-name: App tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Node Packages
        working-directory: ./app
        run: npm ci
      - name: Run Tests
        working-directory: ./app
        run: npm test -- --configuration=ci
