name: Campaigner App Tester
run-name: App tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Node Packages
        working-directory: ./app
        run: npm ci
      - name: Run Tests
        working-directory: ./app
        run: npm test -- --configuration=ci
  build:
    runs-on: ubuntu-latest
    needs: tests
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Build Angular App
        working-directory: ./app
        run: npm build -c production
      - name: Tar Angular app
        working-directory: ./app
        run: tar cvfj campaigner-app.tbz dist/campaigner-app
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: campaigner-app
          path: ./app/campaigner-app.tbz
          compression-level: 0
          overwrite: true
  build-electron:
    runs-on: ubuntu-latest
    needs:
      - tests
      - build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Packaging
        run: |
          sudo apt-get install -y fakeroot dpkg
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: campaigner-app
          path: ./electron
      - name: Unpack Tar
        working-directory: ./electron
        run: |
          gunzip campaigner-app.zip
          mkdir app
          cd app
          tar xvf ../campaigner-app.tbz
      - name: Build Electron bundle
        working-directory: ./electron
        run: |
          npm make
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./electron/out/make/deb/**/*.deb
            ./electron/out/make/zip/**/*.zip
